- Makefile
- README.md
- src/audit_analyser.py
- src/compliance/github_webhook_compliance.py
- src/config/config.py
- tests/compliance/test_github_webhook_compliance.py
- tests/config/test_config.py
- tests/fixtures/github_webhook_compliance.py
- tests/test_audit_analyser.py
- tests/test_compliance_alerter.py
- PSEC-1419 Adds logic to alert on github webhook compliance
- PSEC-1419 Changes webhook report compliance report structure. Adds startswith check on report type
> Adds logic to alert on github webhook compliance

- src/compliance/github_webhook_compliance.py
- tests/compliance/test_github_webhook_compliance.py
- tests/fixtures/github_webhook_compliance.py
- tests/test_compliance_alerter.py
This reverts commit 1a36da697e908be5983d0440e997f0b78e3a2c60.
> Revert "BAU Triple backticks for webhook host name to stop slack link clicks (#23)"

- src/compliance/s3_compliance.py
- tests/compliance/test_s3_compliance.py
- tests/fixtures/s3_compliance.py
- tests/fixtures/s3_compliance_alerter.py
- WIP - add check for bucket logging
- BAU Fixes test by adding to compliance alerter fixture
> Adds logging check for s3 audit

- src/config/config.py
- tests/config/test_config.py
- tests/test_compliance_alerter.py
It has been replaced by an api call in de8b92fcea5bc7d494fd1bd8bb4445c344077dbe
Co-Authored-By: Antoine <achatain@users.noreply.github.com>
> remove account mapping config

- src/audit_analyser.py
- src/clients/aws_org_client.py
- src/compliance/github_compliance.py
- src/compliance/github_webhook_compliance.py
- src/compliance_alerter.py
- src/config/config.py
- src/data/account.py
- src/data/findings.py
- src/notification_mapper.py
- src/sns/guardduty.py
- tests/clients/test_aws_org_client.py
- tests/compliance/test_github_compliance.py
- tests/compliance/test_github_webhook_compliance.py
- tests/config/test_config.py
- tests/sns/test_codebuild.py
- tests/sns/test_codepipeline.py
- tests/sns/test_guardduty.py
- tests/test_compliance_alerter.py
- tests/test_notification_mapper.py
- tests/test_types_generator.py
Co-Authored-By: Antoine <achatain@users.noreply.github.com>
> look up team name from account org tags

- src/compliance/s3_compliance.py
- tests/compliance/test_s3_compliance.py
- tests/fixtures/s3_compliance.py
- tests/fixtures/s3_compliance_alerter.py
PSEC-1526 Added KMS key rotation compliance for buckets
> PSEC-1526 Adds check for s3 audit kms key rotation check

- src/audit_analyser.py
- src/compliance/s3_compliance.py
- src/compliance/summarised_s3_compliance.py
- src/config/config.py
- src/data/findings.py
- tests/compliance/test_s3_compliance.py
- tests/fixtures/s3_compliance.py
- tests/test_compliance_alerter.py
Co-authored-by: Kabbas99 <44403906+Kabbas99@users.noreply.github.com>
> [PSEC-1457] Produce per-account findings from per-bucket findings

- src/compliance/summarised_s3_compliance.py
- tests/compliance/test_s3_compliance.py
Co-authored-by: Kabbas99 <44403906+Kabbas99@users.noreply.github.com>
> [PSEC-1457] Improve summarised S3 alert format

- src/compliance/s3_compliance.py
- tests/compliance/test_s3_compliance.py
> [PSEC-1457] Better S3 alerts wording

- lambda.Dockerfile
This is so we get the latest security updates ect
> run apt-get upgrade at docker build

- src/audit_analyser.py
- src/compliance/vpc_peering_compliance.py
- src/config/config.py
- tests/compliance/test_vpc_peering_compliance.py
- tests/config/test_config.py
- tests/fixtures/vpc_peering_compliance.py
- tests/test_audit_analyser.py
- tests/test_compliance_alerter.py
Co-authored-by: Freshrojek <jnboyer1@gmail.com>
> [PSEC-1546] Compliance alerting for VPC peering audit

- src/compliance/ec2_compliance.py
- tests/compliance/test_ec2_compliance.py
> test ec2 findings output

- Pipfile
- Pipfile.lock
- src/compliance_alerter.py
- src/config/config.py
- tests/compliance/test_github_webhook_compliance.py
- tests/compliance/test_s3_compliance.py
- tests/config/test_config.py
- tests/sns/test_guardduty.py
- tests/test_audit_analyser.py
- tests/test_compliance_alerter.py
Refactor platsec-compliance-alerting code and unit tests
**Why?**
The code has been refactored following dependency injection pattern so as to surface 'hidden' dependencies, and improve testability of the code.
> PSEC-1933-unit-test-refactor

- src/compliance/ssm_compliance.py
- tests/compliance/test_ssm_compliance.py
Update ssm compliance alert description
> PSEC-1953-ssm-document-alert-description

- src/compliance_alerter.py
- src/sns/aws_health.py
- tests/resources/health_event.json
- tests/resources/health_message.json
- tests/sns/test_aws_health.py
- tests/test_compliance_alerter.py
This sends all health events to slack (for now)
> handle aws health messages

- src/config/notification_mapping_config.py
- tests/config/test_notification_mapping.py
- tests/resources/health_message.json
Notification config support for 'pagerduty_service' field
> PSEC-1966-pagerduty

- src/sns/aws_health.py
- tests/sns/test_aws_health.py
Update pagerduty notification custom details with meaningful data
> PSEC-1966-pagerduty-custom-details

- src/compliance_alerter.py
- tests/test_compliance_alerter.py
Ensures only an SNS event is proceesed for pagerduty notification
> PSEC-1966-bug-fix

- src/compliance_alerter.py
- src/sns/aws_health.py
- tests/sns/test_aws_health.py
- tests/test_compliance_alerter.py
Add runbook link to pagerduty alert
> PSEC-1966-runbook

- src/sns/aws_health.py
- tests/sns/test_aws_health.py
> PSEC-1966-runbook-1

- src/notification_mapper.py
- tests/test_notification_mapper.py
This reverts commit 08ace9b0ae28f17e9c2ee8446986dc49e76e6868.
> Revert "PSEC-2096 trying with exclamation maek"

- src/notification_mapper.py
- tests/test_notification_mapper.py
This reverts commit d5a5ae47fd4baecb5c959e0250d1ca32c8e62688.
> Revert "PSEC-2096 trying with an additional at symbol"

- src/data/slack_message.py
- src/notification_mapper.py
- tests/notifiers/test_slack_notifier.py
- tests/test_compliance_alerter.py
- PSEC-2096 testing notify in attachements
- PSEC-2096 striiping out @ slack handle
> PSEC 2096 message fix

- src/notification_mapper.py
- tests/test_notification_mapper.py
This reverts commit f8e2e6609e6d23c799bea1a4d64b83595c5d513d.
> Revert "PSEC-2096 trying @ separately"

- src/compliance/github_webhook_compliance.py
- tests/compliance/test_github_webhook_compliance.py
Logging the url to allow platsec access to the information.
> PSEC-2430 Logging non-compliant webhooks
